name: 'Captain CI example'
on:
  pull_request:
  push:
    paths-ignore:
      - README.md
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: rwx-research/setup-captain@v1
      - name: Run tests
        run: |
          captain run \
            --suite-id captian-examples-xunit2 \
            --test-results TestResults/TestResults.xml \
            -- dotnet test --logger "xunit;LogFileName=TestResults.xml" --results-directory "TestResults"
        env:
          RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}
